### ISSUE TITLE
Add support for sam invoke to Makefile

### ISSUE THREAD

**Issue by ghost** [aws-samples/cookiecutter-aws-sam-python#14]
# Add support for `sam invoke` to Makefile

Update the Makefile to include support for `make invoke`

## Context

There may be a time where a developer wishes to test functions that are not linked to an API gateway facade. It may be desireable to simply develop and run `make invoke SERVICE=first_function EVENT=first_function_event.json` a part of development workflow.

## Problem statement

The current Makefile implementation assumes that functions developed will be wrapped by API gateway.

## Proposed Solution

Add a make target that enables support for `make invoke`

**Comment by heitorlessa** [comment]
Resolving this now as your PR has been merged :) Thanks again!!!!
