### ISSUE TITLE
make test results in no module named pytest

### ISSUE THREAD

**Issue by mjgorman** [aws-samples/cookiecutter-aws-sam-python#18]
When running make test it fails due to missing pytest. It is in the Pipfile and lock.. It seems as if make install isn't actually installing anything based on the output from the virtualenv/lib/python3.6/site-packages/

**Comment by mjgorman** [comment]
appears when it creates the virtualenv it drops into an active shell of the virtualenv and stops before actually installing anything. Then if you exit error provided is 
```
sh-3.2$ exit
exit
/bin/sh: @pipenv: command not found
make: *** [_install_packages] Error 127

```

**Comment by heitorlessa** [comment]
hi @mjgorman did you run: ``make install`` before running ``make test``?

Make install will do both `pipenv install` (prod dependencies) and `pipenv install -D` (dev deps which includes pytest).

```make
_install_dev_packages:
	$(info [*] Install required dev-packages...)
	@$(PIPENV) shell \
	&& @$(PIPENV) install -d
```

**Comment by heitorlessa** [comment]
I'm resolving this due to inactivity. Please do re-open if you're still experiencing this issue.

**Comment by relifeted** [comment]
I think the problem is, the install command always run **after** shell exit, because you are using `&&`, so there are no modules was installed before running into the shell.
