### ISSUE TITLE
Add DOCKER flag to make build

### ISSUE THREAD

**Issue by killswitch-GUI** [aws-samples/cookiecutter-aws-sam-python#22]
I came across an issue where using docker build was essential for building psycopg2. I did some edits to the makefile to allow Docker container builds so I got the proper `.so` file for the lib. ex:

Maybe this is worth adding to the project? Let me know Ill open a pull req and do the proper testing fully. 
```
package: _check_service_definition ##=> Builds package using Docker Lambda container
ifeq ($(DOCKER),1)
	$(info [*] Cleaning up local dev/builds before build task...)
	@$(MAKE) clean SERVICE="${SERVICE}"
	$(info [+] Packaging service '$(SERVICE)' using Docker Lambda -- This may take a while...)
	docker run -v $$PWD:/var/task -it lambci/lambda:build-python3.6 /bin/bash -c 'make _package SERVICE="${SERVICE}"'
else
	$(info [*] Cleaning up local builds before build task...)
	@$(MAKE) clean SERVICE="${SERVICE}"
	$(info [+] Packaging service '$(SERVICE)' -- This may take a while...)
	@$(MAKE) _package SERVICE="${SERVICE}"
endif

build: _check_service_definition _clone_service_to_build ##=> Same as package except that we don't create a ZIP
ifeq ($(DOCKER),1)
	$(info [+] Packaging service '$(SERVICE)' using Docker Lambda -- This may take a while...)
	docker run -v $$PWD:/var/task -it lambci/lambda:build-python3.6 /bin/bash -c 'make _install_deps SERVICE="${SERVICE}"'
else
	@$(MAKE) _install_deps SERVICE="${SERVICE}"
endif
```

**Comment by heitorlessa** [comment]
Absolutely - Please open up a PR and reference this and I'be more than happy to try this out. 

One of the main advantages of the build target is to create a hard link so you don't have to mess around with the `build` folder and keep focusing on your app. If that doesn't break this functionality, which I don't think it does, then great!

**Comment by killswitch-GUI** [comment]
Awesome Ill clean it up and push a PR @heitorlessa !

**Comment by heitorlessa** [comment]
Thank YOU ;)
