### ISSUE TITLE
`make package` fails due to `ln` on macOS

### ISSUE THREAD

**Issue by miketheman** [aws-samples/cookiecutter-aws-sam-python#27]
On macOS 10.14.5 (18F132)

```shellsession
$ make package SERVICE=first_function
[*] Checking whether service first_function exists...
[*] Cleaning up local builds before build task...
[+] Packaging service 'first_function' -- This may take a while...
[*] Who needs all that anyway? Destroying environment....
rm -rf ./first_function/build
rm -rf ./first_function.zip
[+] Setting permissions for files under first_function/
[+] Setting permissions for directories under first_function/
[+] Cloning resource_records directory structure to first_function/build
[+] Cloning source files from resource_records to first_function/build
find first_function/ -type f -exec chmod go+r {} \;
find first_function/ -type d -exec chmod go+rx {} \;
rsync -a -f "+ */" -f "- *" first_function/ first_function/build/
rm -f .results.txt
[*] Checking whether service first_function exists...
[+] Installing 'first_function' dependencies..."
Requirement already satisfied: pipenv in /usr/local/lib/python3.7/site-packages (2018.11.26)
Requirement already satisfied: pip>=9.0.1 in /usr/local/lib/python3.7/site-packages (from pipenv) (19.0.3)
Requirement already satisfied: virtualenv in /usr/local/lib/python3.7/site-packages (from pipenv) (16.2.0)
Requirement already satisfied: setuptools>=36.2.1 in /usr/local/lib/python3.7/site-packages (from pipenv) (40.8.0)
Requirement already satisfied: virtualenv-clone>=0.2.5 in /usr/local/lib/python3.7/site-packages (from pipenv) (0.5.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/site-packages (from pipenv) (2019.3.9)
Looking in indexes: https://pypi.python.org/simple
Collecting aws-xray-sdk==2.4.2 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/58/f2/79f7918f4ddeec525742ddd4607abe4a82a29a6bc4c7e297995f59a18965/aws_xray_sdk-2.4.2-py2.py3-none-any.whl
Collecting boto3==1.9.158 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/cd/b0/8e67d52f8787370828709fe4cad39184e65f3fec28023b78c2556a04be0c/boto3-1.9.158-py2.py3-none-any.whl
Collecting botocore==1.12.158 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/18/21/1e6f12ef2642786bda935f9936bfe3a3f19466a1f3f7e079053421a39f0a/botocore-1.12.158-py2.py3-none-any.whl
Collecting docutils==0.14 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl
Collecting future==0.17.1 (from -r requirements.txt (line 6))
Collecting jmespath==0.9.4 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting jsonpickle==1.2 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/07/07/c157520a3ebd166c8c24c6ae0ecae7c3968eb4653ff0e5af369bb82f004d/jsonpickle-1.2-py2.py3-none-any.whl
Collecting python-dateutil==2.8.0 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting s3transfer==0.2.0 (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/d7/de/5737f602e22073ecbded7a0c590707085e154e32b68d86545dcc31004c02/s3transfer-0.2.0-py2.py3-none-any.whl
Collecting six==1.12.0 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting urllib3==1.25.3 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl
Collecting wrapt==1.11.1 (from -r requirements.txt (line 13))
Installing collected packages: jmespath, docutils, urllib3, six, python-dateutil, botocore, wrapt, jsonpickle, future, aws-xray-sdk, s3transfer, boto3
Successfully installed aws-xray-sdk-2.4.2 boto3-1.9.158 botocore-1.12.158 docutils-0.14 future-0.17.1 jmespath-0.9.4 jsonpickle-1.2 python-dateutil-2.8.0 s3transfer-0.2.0 six-1.12.0 urllib3-1.25.3 wrapt-1.11.1
ln: events: Is a directory
make[1]: *** [_install_deps] Error 1
make: *** [package] Error 2

$ ls -l events
total 8
-rw-r--r--  1 miketheman  staff  23 May 29 23:52 first_function_event.json
```

Stems from:

https://github.com/aws-samples/cookiecutter-aws-sam-python/blob/2fa3f449af79eb5de42d93cec732c9a428b76366/%7B%7B%20cookiecutter.project_name%20%7D%7D/Makefile#L149

macOS seems to disallow hard linking of directories, and the command fails.
See more at https://stackoverflow.com/questions/80875/what-is-the-unix-command-to-create-a-hardlink-to-a-directory-in-os-x

This makes commands like `make build/package` fail. Is there a decent workaround other than simply stopping that practice?

**Comment by heitorlessa** [comment]
Hi Mike - Thanks for opening this.

I believe that came from a PR as you cannot indeed create hard links
targeting a folder but symlink - That’s Unix in general hence the
workaround[1] to allow hot reloading.


Could you comment that line as that’s not necessary until I come back from
holidays next Thursday and clean this up?

Also, what are your thoughts on moving all this to use Sam build?

The only advantage this Makefile provides today is the hot reloading
feature.

Thanks again and have a great weekend

[1]
https://github.com/aws-samples/cookiecutter-aws-sam-python/blob/2fa3f449af79eb5de42d93cec732c9a428b76366/%7B%7B%20cookiecutter.project_name%20%7D%7D/Makefile

**Comment by miketheman** [comment]
Thanks @heitorlessa for checking in while on vacation!
I've commented out the line and it's continuing the build process.

I think I'm definitely interested in using the `sam build` approach - I was also a little confused that the Makefile didn't encompass all the necessary steps to do something like `make deploy` that would build, package, and deploy all in one step.

**Comment by heitorlessa** [comment]
> Thanks @heitorlessa for checking in while on vacation!
> I've commented out the line and it's continuing the build process.
> 
> I think I'm definitely interested in using the `sam build` approach - I was also a little confused that the Makefile didn't encompass all the necessary steps to do something like `make deploy` that would build, package, and deploy all in one step.

Great - I will create a WIP PR to move to `sam build` and possibly remove that `Makefile` altogether as it's no longer required.

We initially had package and deploy all in one go, though it turned out not everyone knew how to customize to their own Stack Parameters and the likes -- Mostly an understanding of Makefile executing each command in a new shell. 

 I'll leave this open and reference it in a PR to make all of this simpler - hopefully by next Friday due to travels. 

Thanks for the patience

**Comment by heitorlessa** [comment]
PR that I'll update as soon as I test `watchdog` to avoid a regression in developer experience (hot reloading): https://github.com/aws-samples/cookiecutter-aws-sam-python/pull/25
