### ISSUE TITLE
Template generation might fail if python environment is not setup correctly

### ISSUE THREAD

**Issue by mndeveci** [aws-samples/cookiecutter-aws-sam-python#45]
Hi team,

A customer reported an issue while trying to generate a template with SAM CLI using this repository. You can read details here: https://github.com/aws/aws-sam-cli/issues/5057

In short, their python environment was not setup correctly, therefore post hooks defined in this repository have failed to execute and template generation failed in the end.

I will recommend pointing this out specifically in the README file. We could also provide an FAQ kind of section where we can guide them correct setup to use this template while generating a new application.

Thanks!

**Comment by heitorlessa** [comment]
Fixed it, thank you so much for flagging it. Powertools staged docs are being rebuilt as we speak to refer to the newer SAM CLI template instead too.

https://github.com/aws-samples/cookiecutter-aws-sam-python/commit/7a8e97e1bcb4c74c1f609ecef27f7a9495705907
