### ISSUE TITLE
[Discussion] Adding a pipeline for this example

### ISSUE THREAD

**Issue by heitorlessa** [aws-samples/cookiecutter-aws-sam-python#8]
# Proposal: Add CI/CD Pipeline for this template

Last updated: June 6th

## Abstract

This proposal aims to add an additional capability to include a CI/CD Pipeline after an user completes its first deployment, so that it becomes a progressive experience after getting used to the programming and deployment model without having to enforce that a Pipeline should be used from Day 1.

## Background

When customers complete the steps outlined in the README upon the project generation they expressed they'd like to progress in their experience and understand how to create a Pipeline that will help them "productionize" their Serverless App, however they may not have experience with all services required to do so.

## Proposal

I propose 2 methods to implement this that wouldn't affect the current experience this template provides:

1. Develop a CI/CD pipeline in a separate Github repo that could be pulled into an existing Python project
2. Include a pipeline option in `cookiecutter.json` and if chosen `buildspec.yaml` and `pipeline.yaml` would be added upon project generation

Here's how the Developer Experience would look like for method 1:

1. Initialize a new app: ``sam init --runtime python`` or ``sam init --location gh:aws-samples/cookiecutter-aws-sam-python``
2. Work on business logic and deploy their service without any pipeline
3. Once they feel comfortable with the environment they can add generate a 3-stage CI/CD pipeline with ``sam init --location gh:aws-samples/cookiecutter-aws-sam-pipeline``
4. This would add 3 files to their current project folder: `buildspec.yaml` (if not already created), `pipeline.yaml` and `Pipeline-Instructions.MD`
    - `buildspec.yaml` would contain comments on how to create a build step (e.g install deps here, run unit tests her, etc.) including the `sam package` command that will work for the pipeline
    - `pipeline.yaml` would contain a Cloudformation Template that has everything they'd need to generate this CI/CD pipeline including comments on how to extend or understand options used
    - `Pipeline-Instructions.MD` would contain information about
        + How the Pipeline is constructed
        + Any changes that may be required to customize the experience (e.g. Single Account vs Multi-Account)
        + How to create a Cloudformation stack to generate this pipeline
        + How to push their code to the new source code repository

Here's how the Developer Experience would look like for method 2:

1. Initialize a new app: ``sam init --runtime python`` or ``sam init --location gh:aws-samples/cookiecutter-aws-sam-python``
2. Work on business logic and deploy their service without any pipeline
3. `buildspec.yaml` and `pipeline.yaml` would be included upon project generation and already customized with defaults for the chosen runtime
4. `README.MD` would be extended to include details on how to generate this CI/CD pipeline under `Appendix`

## Rationale

Each method has its pros and cons and this aims to outline them to aid with a decision alongside the comments by the community too.

**Develop a CI/CD pipeline in a separate Github repo**

Pros: 

* Clean start and separation as pipeline can have different contributors
* One could fork and create a pipeline for any Runtime with their own defaults in the future with subtle changes
* Can add a pipeline to an existing project without impacting it

Cons:

* One needs to know of this template's existence otherwise it wouldn't know how to use it

**Include a pipeline option upon project generation**

Pros: 

* Single repo and easier to correlate target project for this pipeline
* Forking this repository for other runtimes would include the entire package idea (project structure, tests and pipeline)

Cons:

* Customers would need to re-initialize this project only to have access to the pipeline feature

## Compatibility

Option 1 doesn't break compatibility whilst the second would only affect existing customers who already initialized a project with this template. 

## Implementation

Implementation for either methods would be similar so here are the common parts:

* Create a `pipeline.yaml` that will implement a 3-stage CI/CD CodePipeline pipeline that will include:
    - **CodeCommit** or **Github** as a source code repository
    - **CodeBuild**  for running tests, packaging and any security tests
    - **Cloudformation** to deploy the SAM stack
    - **S3 Bucket** for storing Build Artifacts
    - **Single or Multi-Account option** so an user can have placeholders and an explanation as to how to use that in a multi-account scenario
* Create a `buildspec.yaml` that will implement the build steps for CodeBuild that will include:
    - Run all tests with a coverage baseline
    - Packaging the Python project with one or more functions
    - Create a SAM package
* Append `Pipeline` into Appendix to include the following instructions:
    - How to create a pipeline stack
    - How to initialize a repo to connect git changes to this newly created pipeline
    - How to add Pipeline metrics (# of deployments, lead time, etc.)
* Extend `hooks` to not overwrite any existing `buildspec.yaml`

For the second approach the following would be needed in addition to the above:

* Extend `cookiecutter.json` and add a `include_pipeline` option and default to `n`
* Extend logic in `hooks` to clean up `buildspec.yaml` and `pipeline.yaml` if `include_pipeline` isn't chosen

**Comment by heitorlessa** [comment]
cc @Nr18  @h1f1x

**Comment by Nr18** [comment]
My preference goes to including the pipeline in this project. To address the con of this option #8 might offer a solution by adding a command to create the pipeline afterwards?

**Comment by h1f1x** [comment]
I like the idea to show - right from the start - the deployment with CI/CD. 
But the possibility to create a generic pipeline for any Runtime independently is a strong pro. And also the other pros for (1).
 
For (2) I see another con: improvements and changes in the pipeline will not propagate to all other runtimes (which based on this python repo).
To mitigate the con of the separated repositories, we can add this repo to the readme.

So I would prefer (1) at the moment.

**Comment by heitorlessa** [comment]
Thanks for the input @Nr18 and @h1f1x -- I've just updated the Proposal to reflect how the Developer Experience would look like.

I've been tinkering with both approaches and found that providing a Generic Pipeline and a Generic Build in a separate repo seems the most straightforward. 

Here's my final thoughts after experimenting with both and noticing how much duplication happens on method 2:

* Make a PR for `aws-sam-cli` and include a `buildspec.yaml` for each runtime we support
* Publish a generic `pipeline.yaml` and a `buildspec.yaml` into a separate repo
    - This generic `buildspec.yaml` will mostly have comments and only a `sam package` with the output that the Pipeline expects
    - This should allow for anyone to add a SAM pipeline to any existing project and have a generic build OR to only add a generic pipeline and exclude the generic Build if they already have a `buildspec.yaml` (in simple words, not to overwrite)

This way we can have the best of both worlds:

1) Customers would be able to run CodeBuild Locally to get used to creating/running Builds and optimising for that in a progressive manner
2) CI/CD Pipeline in a separate repo and therefore can have dedicated improvements (e.g. better multi-account, etc.)
3) Anyone can fork such Pipeline and Build and add their own defaults for their own runtime

What do you think?

Edited: Added bullet points to further clarify this 2-step process

**Comment by h1f1x** [comment]
I am not sure if I got excatly what you wanna change. 
Here what I understood:
You want to change the sam init to provide a generic buildspec.yaml.
This needs to be requested in *sam*, correct?
The pipeline.yaml you want to have in a separate Repo.

If this is not correct, maybe show: what is in this: CI/CD Pipeline in a separate repo?

**Comment by heitorlessa** [comment]
That's right! It's a 2-step process:

1) I want to make a PR for SAM CLI to include a `buildspec.yaml` for each Runtime we support
2) I want to publish a generic CI/CD pipeline in a separate repo

**Comment by heitorlessa** [comment]
Published MVP with Single-Account support for CodeCommit and GitHub: ``sam init --location gh:aws-samples/cookiecutter-aws-sam-pipeline``

Let me know what you think and I will work on Multi-account in the coming months

**Comment by h1f1x** [comment]
@heitorlessa :I will take a deeper look into this over the next days .... Maybe you will find some issues in https://github.com/aws-samples/cookiecutter-aws-sam-pipeline/issues

**Comment by heitorlessa** [comment]
Thanks a lot @h1f1x as usual ;) You and @Nr18 have been fundamental for this.

Just pushed the latest there to enable Travis and as soon as anyone with a spare cycle can review I will merge, close this issue and do the same for this repo

**Comment by heitorlessa** [comment]
I'm going to resolve this now as the pipeline sample it's in use for quite some time and it even includes tests now.

Thanks a lot for your thoughts, iterations and trials @h1f1x  and @Nr18. Appreciate your help very much
