### ISSUE TITLE
[Discussion] Convert Makefile into a Python script

### ISSUE THREAD

**Issue by heitorlessa** [aws-samples/cookiecutter-aws-sam-python#9]
# Proposal: Convert Makefile into a Python script

Last updated: June 6th

## Abstract

As of today, OSX and Linux users are able to have hot-reloading thanks to Makefile logic that creates hard-links on a given service/folder, however this is currently not possible for Windows due to Operating Systems differences.

Windows hard links seem to be supported when using Python and this proposal aims to convert this Makefile to make these features more accessible to everyone. Additionally, this could open the opportunity to add other mechanisms such as deployment asked here https://github.com/aws-samples/cookiecutter-aws-sam-python/pull/2 and make the packaging feature more explicit.

## Background

When Windows customers try to use Makefile for hot-reloading or easier Python packaging they need to install Git Bash or Windows Sub-system in order to get access to UNIX tools to make this work.

Linux and OSX users also expressed they'd like to have `requirements.txt` or `Pipfile` per function and not at the project level as well as a `deploy` target, of which would add complexity to Makefile and error prone not to mention that is difficult to test Makefile changes today.

## Proposal

I propose porting Makefile essential features to a Python CLI script that would include:

* [build](https://github.com/aws-samples/cookiecutter-aws-sam-python/blob/master/%7B%7B%20cookiecutter.project_name%20%7D%7D/Makefile#L53)
* [package](https://github.com/aws-samples/cookiecutter-aws-sam-python/blob/master/%7B%7B%20cookiecutter.project_name%20%7D%7D/Makefile#L40)
* [run](https://github.com/aws-samples/cookiecutter-aws-sam-python/blob/master/%7B%7B%20cookiecutter.project_name%20%7D%7D/Makefile#L56)
* [test](https://github.com/aws-samples/cookiecutter-aws-sam-python/blob/master/%7B%7B%20cookiecutter.project_name%20%7D%7D/Makefile#L61)
* [clean](https://github.com/aws-samples/cookiecutter-aws-sam-python/blob/master/%7B%7B%20cookiecutter.project_name%20%7D%7D/Makefile#L28)

## Rationale

By implementing this Python CLI script we could also give more options to customers and be less opinionated as to where their dependencies should be declared and more importantly allow for testing this functionality as Makefile is only for advanced users.

Difficulty here is deciding on a name for this Python CLI script because `setup.py` is widely used for Python Packaging with setuptools and `manage.py` is used for Django Apps so perhaps `bootstrap.py` could fit the bill here.

Also needs some thinking whether it makes sense to use only `requirements.txt` to simplify initial design or to support both `Pipfile` and `requirements.txt`.

## Compatibility

No breaking change to the application itself

## Implementation

This could be implemented using Python Click or pure Python Argparse to avoid additional dependencies:

* Move `test` folder inside the function 
* Create a `test` folder to explicitly have tests for this Python CLI script
* Add the following targets
    - [build](https://github.com/aws-samples/cookiecutter-aws-sam-python/blob/master/%7B%7B%20cookiecutter.project_name%20%7D%7D/Makefile#L53)
        - Install deps and creates structure for hot-reloading without having to build a wrapper or anything
        - **Define parameter** for Source Code directory and optional for requirements.txt/Pipfile
    - [package](https://github.com/aws-samples/cookiecutter-aws-sam-python/blob/master/%7B%7B%20cookiecutter.project_name%20%7D%7D/Makefile#L40)
         - Install deps and builds a Lambda compliant ZIP package and optionally with LambCI Docker Lambda Runtime when needed
         - **Define parameter** to allow straight up `zip` instead of installing deps in case they are already ready  
    - [run](https://github.com/aws-samples/cookiecutter-aws-sam-python/blob/master/%7B%7B%20cookiecutter.project_name%20%7D%7D/Makefile#L56)
        - Runs `sam local start-api` and supports for running Lambda containers within a Docker network
    - [test](https://github.com/aws-samples/cookiecutter-aws-sam-python/blob/master/%7B%7B%20cookiecutter.project_name%20%7D%7D/Makefile#L61)
        - Runs `pytest` and set `XRAY` env to run that locally
        - **Define parameter** for specifying tests folder
* [clean](https://github.com/aws-samples/cookiecutter-aws-sam-python/blob/master/%7B%7B%20cookiecutter.project_name%20%7D%7D/Makefile#L28)
    - Deletes zip file and build folder

**Comment by Nr18** [comment]
Love the idea it’s not mentioned in the issue but currently you need to build each function separate will the new build target build all the services or just the one?

Would love to have a single build command for all functions especially when you want to do something with stepfunctions your amount of functions grow rapidly. 

That being said a create function command might be usefull that do some groundwork like create the directories/tests/requirements.txt for you.

**Comment by Nr18** [comment]
In my current project i created a ‘Makefile’ in the function dir and use that to install the requirements the reason why i used a Makefile was that i have 2 types of requirements:

- Normal python packages that can be installed via ‘requirements.txt’
- Custom binaries with libraries zipped that are used from the function (things like ffmpeg and other libraries that typically are invoked by lambda)

Not sure how that will fit in this proposal?

**Comment by h1f1x** [comment]
Hi,

I liked the idea of having a makefile instead of a python script. Acceptance (of developers) seems a little higher these times. And it seems a little bit of reinventing the wheel?
I am using [pybuilder](https://github.com/pybuilder/) for some years. Maybe you take a look into it [1].
This seems to be doing stuff you like, but introduce another dependency.

[1] https://www.youtube.com/watch?v=jufUqH3bDG0

**Comment by h1f1x** [comment]
At the moment I am in favour of the makefile. To know this is imho very useful for developers.
Developing a python solution seem to be a little out of scope and not a small effort.

**Comment by heitorlessa** [comment]
I had a look around and found that the good old Fabric split the tasks part into its own lib that possibly can make this idea viable without creating a standalone CLI: https://github.com/pyinvoke/invoke

Haven't tried yet nor know if that works on Windows (Fabric used to so I expect yes as an answer).

I'll give this a try as soon as we tidy up the pipeline repo and this one to ensure new PRs follow a standard (pylint, etc.)

**Comment by heitorlessa** [comment]
This will no longer be needed due to SAM now supports `build`
